### ISSUE TITLE
Numbers with thousands separators are sorted alphabetically

### ISSUE THREAD

**Issue by hpollinger** [DanielHeath/sortable#2]
Its a great little tool you provide and I'd like to help to improve it further!

I tried to sort the last column on this page: https://shinyrates.com/ but obviously sortable thinks numbers with thousands separators are text and sorts them alphabetically.

Sorting the second last column with the fractions numerically correct would also be nice but thats probably too specific.

Depending on the language, either dots or commas are used as thousands separators - while the other punctuation is used as the decimal separator. For example, in English, commas are thousands, dots are decimal separators. In German (and AFAIK all other continental European languages) dots are thousands, commas are decimal separators.
There are more complicated cases, too, but that would be too much.

How to find out what format is used:
The trivial case is if a sequence of digits contains both punctuation signs - the first one(s) are thousands separators, the last one is the decimal separator.

If it contains only one punctuation sign:
* If there are more than three digits before that sign, it's the decimal separator.
* If there are more than three digits after that sign, it's the decimal separator.
* If there are less than three digits after that sign, it's the decimal separator.
* If there is the same amount of digits after that sign for all numbers in that column, simply assume its the decimal separator in all cases. Then it doesn't matter for sorting what it really is.
* If there are three digits after that sign for some, but less or more than three digits after that sign for other numbers in the column, assume its the decimal separator.

After filtering out all these cases, what remains causes trouble:
* In columns with numbers of different length, some having the sign and having always three digits after it, some don't have that sign. It could be both - and sorting is affected by the meaning of that sign.
I would assume that in all tables containing proper data, if some numbers are specified to the third digit after the sign, all other numbers would also contain a decimal separator, even if there are just zeros after that separator, so in this case I'd assume it's a thousands separator.

Did I forget some case?

**Comment by DanielHeath** [comment]
Alright, should be working better now :)



Thanks,
Daniel Heath

**Comment by hpollinger** [comment]
Works like a charm now, thank you!

**Comment by kurupted** [comment]
Doesn't work with currencies still. I get, eg
$1,000
$15,000
$2,000

I asked ChatGPT how to fix it -- I'm not sure how correct this is:

`The issue is your number data has the dollar ($) sign attached to it, making it sort numerically incorrect because it's being sorted as a string instead of a number. To fix this, you should strip off the '$' sign before sorting. Here is an example of how you can do this:

1. Modify your "parseNumberFromString" function to remove the dollar sign ('$') before parsing:

```javascript
function parseNumberFromString(str) {
    str = str.replace(/[$,]/g, ''); // Strip off $ and , (comma) before parsing

    let num;
    return num = str.match(/^\((\d+(?:\.\d+)?)\)$/) ? -1 * Number(str.slice(1,-1)) : Number(str), num
}
```

This regular expression `/$,/g` will remove all occurrences of dollar signs and commas from the number.

2. Alternatively, you can consider adding a new `currency` inferableClass to properly sort currencies:

```javascript
const inferableClasses = {
    // ... other classes
    currency: {
        regexp: /^\$\d+(?:[.,]\d{0,2})$/,
        class: "currency-sort",
        count: 0
    } // currency-sort will match $ followed by digits with optional two decimal places
};
```

Then, add a new property `currency` in the `hasThClass` object:

```javascript
const hasThClass = {
    // ... other properties
    currency: th.classList.contains("currency-sort")
};
```

In the `getTableData` function, add a new check for 'currency' and handle the currency data properly:

```javascript
if (hasThClass.currency) {
    // currency-sort handling
    // remove '$' before parsing numbers
    for(let[i, tr] of tableRows.entries()) {
        let currencyContent = column.getColumn(tr, column.spanSum, column.span).textContent;
        currencyContent = currencyContent.replace(/^\$/, ''); // Strip off $
        column.toBeSorted.push(`${currencyContent}#${i}`);
        columnIndexAndTableRow[`${currencyContent}#${i}`] = cellsOrRows(table, tr);
    }
    // continue with sorting as usual
}
```

Remember to add a condition to handle `currency-sort` in `updateTable` function.

_Note: If you apply these changes, remember to include `currency-sort` class in your Table Header (th)._`

**Comment by DanielHeath** [comment]
ChatGPT has proved as useful as it usually is in this instance (suggesting I modify methods that do not exist, for instance).

I'd be happy to accept a (human authored) pull request to add this functionality, though.
